-- Rivo Support Portal: additive migration for the existing Rivo Supabase project.
-- Rivo login bridge: resolve the real Supabase Auth email from the Rivo username.
-- Needed because the Support Portal uses the existing Rivo username/password login.
create or replace function public.rivo_get_login_email(p_username text)
returns text
language sql
security definer
set search_path = public, auth
as $$
  select u.email
  from public.profiles p
  join auth.users u on u.id = p.id
  where lower(p.username) = lower(trim(both '@' from coalesce(p_username, '')))
  limit 1;
$$;
revoke all on function public.rivo_get_login_email(text) from public;
grant execute on function public.rivo_get_login_email(text) to anon, authenticated;

-- Does NOT modify existing Rivo tables or functions. Uses the same auth.users/profiles
-- and the existing rivo_is_admin() function.

create table if not exists public.rivo_support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (char_length(trim(subject)) between 3 and 120),
  category text not null default 'other' check (category in ('account','technical','payment','report','privacy','other')),
  priority text not null default 'normal' check (priority in ('low','normal','high')),
  status text not null default 'open' check (status in ('open','pending','closed')),
  assigned_admin_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create index if not exists rivo_support_tickets_user_idx on public.rivo_support_tickets(user_id, updated_at desc);
create index if not exists rivo_support_tickets_status_idx on public.rivo_support_tickets(status, updated_at desc);
create index if not exists rivo_support_tickets_assigned_idx on public.rivo_support_tickets(assigned_admin_id, status, updated_at desc);

create table if not exists public.rivo_support_messages (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.rivo_support_tickets(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  content text not null default '' check (char_length(trim(content)) <= 4000),
  attachment_path text,
  attachment_type text,
  created_at timestamptz not null default now()
);
create index if not exists rivo_support_messages_ticket_idx on public.rivo_support_messages(ticket_id, created_at asc);

create table if not exists public.rivo_support_events (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.rivo_support_tickets(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists rivo_support_events_ticket_idx on public.rivo_support_events(ticket_id, created_at desc);

alter table public.rivo_support_tickets enable row level security;
alter table public.rivo_support_messages enable row level security;
alter table public.rivo_support_events enable row level security;

-- RLS is defensive; browser mutations still go through controlled RPCs.
drop policy if exists "support_ticket_customer_select" on public.rivo_support_tickets;
create policy "support_ticket_customer_select" on public.rivo_support_tickets for select to authenticated
using (user_id = auth.uid() or public.rivo_is_admin(auth.uid()));

drop policy if exists "support_message_participant_select" on public.rivo_support_messages;
create policy "support_message_participant_select" on public.rivo_support_messages for select to authenticated
using (exists (select 1 from public.rivo_support_tickets t where t.id = ticket_id and (t.user_id = auth.uid() or public.rivo_is_admin(auth.uid()))));

drop policy if exists "support_event_admin_select" on public.rivo_support_events;
create policy "support_event_admin_select" on public.rivo_support_events for select to authenticated
using (public.rivo_is_admin(auth.uid()) or exists (select 1 from public.rivo_support_tickets t where t.id = ticket_id and t.user_id = auth.uid()));

-- Private support attachments. The browser can create signed URLs only after the
-- object passes this policy. Customers access their own folder; admins can access all.
do $$ begin
  insert into storage.buckets (id, name, public)
  values ('rivo-support-media','rivo-support-media',false)
  on conflict (id) do update set public=false;
exception when undefined_table then null; end $$;

drop policy if exists "support_media_insert" on storage.objects;
create policy "support_media_insert" on storage.objects for insert to authenticated
with check (bucket_id = 'rivo-support-media' and (name like auth.uid()::text || '/%'));

drop policy if exists "support_media_select" on storage.objects;
create policy "support_media_select" on storage.objects for select to authenticated
using (bucket_id = 'rivo-support-media' and (name like auth.uid()::text || '/%' or public.rivo_is_admin(auth.uid())));

drop policy if exists "support_media_delete" on storage.objects;
create policy "support_media_delete" on storage.objects for delete to authenticated
using (bucket_id = 'rivo-support-media' and (name like auth.uid()::text || '/%' or public.rivo_is_admin(auth.uid())));

create or replace function public.rivo_support_is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select public.rivo_is_admin(auth.uid());
$$;
revoke all on function public.rivo_support_is_admin() from public;
grant execute on function public.rivo_support_is_admin() to authenticated;

create or replace function public.rivo_support_me()
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare p public.profiles;
begin
  select * into p from public.profiles where id=auth.uid();
  if not found then raise exception 'Profile not found'; end if;
  return jsonb_build_object(
    'id',p.id,
    'username',p.username,
    'display_name',coalesce(p.public_data->>'displayName',p.username),
    'avatar',coalesce(p.public_data->>'avatar','')
  );
end;
$$;
revoke all on function public.rivo_support_me() from public;
grant execute on function public.rivo_support_me() to authenticated;

create or replace function public.rivo_support_create_ticket(p_subject text,p_category text default 'other',p_priority text default 'normal',p_message text default '')
returns jsonb language plpgsql security definer set search_path=public as $$
declare tid uuid;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if char_length(trim(coalesce(p_subject,''))) < 3 then raise exception 'عنوان المشكلة قصير جدًا'; end if;
  insert into public.rivo_support_tickets(user_id,subject,category,priority)
  values(auth.uid(),trim(p_subject),case when p_category in ('account','technical','payment','report','privacy','other') then p_category else 'other' end,case when p_priority in ('low','normal','high') then p_priority else 'normal' end)
  returning id into tid;
  if char_length(trim(coalesce(p_message,''))) > 0 then
    insert into public.rivo_support_messages(ticket_id,sender_id,content) values(tid,auth.uid(),trim(p_message));
    update public.rivo_support_tickets set last_message_at=now(),updated_at=now() where id=tid;
  end if;
  insert into public.rivo_support_events(ticket_id,actor_id,event_type,payload) values(tid,auth.uid(),'created',jsonb_build_object('category',p_category,'priority',p_priority));
  return jsonb_build_object('id',tid);
end;
$$;
revoke all on function public.rivo_support_create_ticket(text,text,text,text) from public;
grant execute on function public.rivo_support_create_ticket(text,text,text,text) to authenticated;

create or replace function public.rivo_support_list_tickets(p_scope text default 'mine',p_status text default 'all',p_limit int default 100,p_offset int default 0)
returns setof jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object(
  'id',t.id,'subject',t.subject,'category',t.category,'priority',t.priority,'status',t.status,
  'status_label',case t.status when 'open' then 'مفتوح' when 'pending' then 'بانتظار الرد' else 'مغلق' end,
  'priority_label',case t.priority when 'high' then 'عالية' when 'low' then 'منخفضة' else 'عادية' end,
  'username',p.username,'updated_at',t.updated_at,'assigned_admin_username',ap.username
)
from public.rivo_support_tickets t
join public.profiles p on p.id=t.user_id
left join public.profiles ap on ap.id=t.assigned_admin_id
where ((coalesce(p_scope,'mine')='mine' and t.user_id=auth.uid()) or (coalesce(p_scope,'mine')='admin' and public.rivo_is_admin(auth.uid())))
  and (coalesce(p_status,'all')='all' or t.status=p_status)
order by t.updated_at desc
limit greatest(1,least(coalesce(p_limit,100),200)) offset greatest(0,coalesce(p_offset,0));
$$;
revoke all on function public.rivo_support_list_tickets(text,text,int,int) from public;
grant execute on function public.rivo_support_list_tickets(text,text,int,int) to authenticated;

create or replace function public.rivo_support_get_ticket(p_ticket_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare t public.rivo_support_tickets; out jsonb; can_see boolean;begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  select * into t from public.rivo_support_tickets where id=p_ticket_id;
  if not found then raise exception 'Ticket not found'; end if;
  can_see := t.user_id=auth.uid() or public.rivo_is_admin(auth.uid());
  if not can_see then raise exception 'Access denied'; end if;
  select jsonb_build_object(
    'id',t.id,'subject',t.subject,'category',t.category,'priority',t.priority,'status',t.status,
    'status_label',case t.status when 'open' then 'مفتوح' when 'pending' then 'بانتظار الرد' else 'مغلق' end,
    'priority_label',case t.priority when 'high' then 'عالية' when 'low' then 'منخفضة' else 'عادية' end,
    'user',jsonb_build_object('id',p.id,'username',p.username,'display_name',coalesce(p.public_data->>'displayName',p.username)),
    'messages',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'sender_id',m.sender_id,'sender_name',coalesce(mp.public_data->>'displayName',mp.username),'content',m.content,'created_at',m.created_at,'attachment_path',m.attachment_path,'attachment_type',m.attachment_type) order by m.created_at asc) from public.rivo_support_messages m join public.profiles mp on mp.id=m.sender_id where m.ticket_id=t.id),'[]'::jsonb)
  ) into out
  from public.profiles p where p.id=t.user_id;
  return out;
end;
$$;
revoke all on function public.rivo_support_get_ticket(uuid) from public;
grant execute on function public.rivo_support_get_ticket(uuid) to authenticated;

create or replace function public.rivo_support_send_message(p_ticket_id uuid,p_content text default '',p_attachment_path text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare t public.rivo_support_tickets; sid uuid:=auth.uid(); mid bigint; admin boolean;begin
  if sid is null then raise exception 'Not authenticated'; end if;
  select * into t from public.rivo_support_tickets where id=p_ticket_id;
  if not found then raise exception 'Ticket not found'; end if;
  admin := public.rivo_is_admin(sid);
  if t.user_id<>sid and not admin then raise exception 'Access denied'; end if;
  if t.status='closed' then raise exception 'البلاغ مغلق. أعد فتحه قبل إرسال رسالة.'; end if;
  if char_length(trim(coalesce(p_content,'')))=0 and nullif(trim(coalesce(p_attachment_path,'')),'') is null then raise exception 'Message is empty'; end if;
  if p_attachment_path is not null and p_attachment_path <> '' and position(sid::text||'/' in p_attachment_path) <> 1 and not admin then raise exception 'Invalid attachment path'; end if;
  insert into public.rivo_support_messages(ticket_id,sender_id,content,attachment_path,attachment_type)
  values(p_ticket_id,sid,trim(coalesce(p_content,'')),nullif(trim(p_attachment_path),''),case when p_attachment_path is null then null else 'image' end)
  returning id into mid;
  update public.rivo_support_tickets set updated_at=now(),last_message_at=now(),status=case when admin then 'pending' else 'open' end where id=p_ticket_id;
  insert into public.rivo_support_events(ticket_id,actor_id,event_type,payload) values(p_ticket_id,sid,'message',jsonb_build_object('message_id',mid));
  return jsonb_build_object('id',mid);
end;
$$;
revoke all on function public.rivo_support_send_message(uuid,text,text) from public;
grant execute on function public.rivo_support_send_message(uuid,text,text) to authenticated;

create or replace function public.rivo_support_assign_ticket(p_ticket_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.rivo_is_admin(auth.uid()) then raise exception 'Access denied'; end if;
  update public.rivo_support_tickets set assigned_admin_id=auth.uid(),status=case when status='closed' then 'open' else status end,updated_at=now() where id=p_ticket_id;
  if not found then raise exception 'Ticket not found'; end if;
  insert into public.rivo_support_events(ticket_id,actor_id,event_type) values(p_ticket_id,auth.uid(),'assigned');
  return true;
end;
$$;
revoke all on function public.rivo_support_assign_ticket(uuid) from public;
grant execute on function public.rivo_support_assign_ticket(uuid) to authenticated;

create or replace function public.rivo_support_release_ticket(p_ticket_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.rivo_is_admin(auth.uid()) then raise exception 'Access denied'; end if;
  update public.rivo_support_tickets set assigned_admin_id=null,updated_at=now() where id=p_ticket_id;
  if not found then raise exception 'Ticket not found'; end if;
  insert into public.rivo_support_events(ticket_id,actor_id,event_type) values(p_ticket_id,auth.uid(),'released');
  return true;
end;
$$;
revoke all on function public.rivo_support_release_ticket(uuid) from public;
grant execute on function public.rivo_support_release_ticket(uuid) to authenticated;

create or replace function public.rivo_support_set_ticket_status(p_ticket_id uuid,p_status text)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.rivo_is_admin(auth.uid()) then raise exception 'Access denied'; end if;
  if p_status not in ('open','pending','closed') then raise exception 'Invalid status'; end if;
  update public.rivo_support_tickets set status=p_status,updated_at=now() where id=p_ticket_id;
  if not found then raise exception 'Ticket not found'; end if;
  insert into public.rivo_support_events(ticket_id,actor_id,event_type,payload) values(p_ticket_id,auth.uid(),'status',jsonb_build_object('status',p_status));
  return true;
end;
$$;
revoke all on function public.rivo_support_set_ticket_status(uuid,text) from public;
grant execute on function public.rivo_support_set_ticket_status(uuid,text) to authenticated;

create or replace function public.rivo_support_user_stats()
returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('open',count(*) filter(where status='open'),'pending',count(*) filter(where status='pending'),'closed',count(*) filter(where status='closed')) from public.rivo_support_tickets where user_id=auth.uid();
$$;
revoke all on function public.rivo_support_user_stats() from public;
grant execute on function public.rivo_support_user_stats() to authenticated;

create or replace function public.rivo_support_admin_stats()
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare r jsonb;begin
  if not public.rivo_is_admin(auth.uid()) then raise exception 'Access denied'; end if;
  select jsonb_build_object('total',count(*),'open',count(*) filter(where status='open'),'pending',count(*) filter(where status='pending'),'closed',count(*) filter(where status='closed'),'unassigned',count(*) filter(where assigned_admin_id is null and status<>'closed'),'today',count(*) filter(where created_at>=date_trunc('day',now()))) into r from public.rivo_support_tickets;
  return r;
end;
$$;
revoke all on function public.rivo_support_admin_stats() from public;
grant execute on function public.rivo_support_admin_stats() to authenticated;

create or replace function public.rivo_support_suggestions(p_category text)
returns setof jsonb language sql immutable as $$
  select v from (values
    (jsonb_build_object('title','مشاكل تسجيل الدخول','body','جرّب اسم المستخدم الصحيح، وتأكد من كلمة المرور. لا ترسل كلمة المرور داخل البلاغ.'),'account'),
    (jsonb_build_object('title','لقطة الشاشة مفيدة','body','أرفق صورة لرسالة الخطأ أو الشاشة التي تظهر فيها المشكلة.'),'technical'),
    (jsonb_build_object('title','الدفع والاشتراك','body','أرفق رقم العملية أو صورة الإيصال، مع إخفاء أي بيانات حساسة.'),'payment'),
    (jsonb_build_object('title','الإبلاغ عن إساءة','body','اذكر اسم الحساب أو رابط المحتوى وسبب البلاغ بوضوح.'),'report'),
    (jsonb_build_object('title','حماية الحساب','body','لا ترسل كلمة المرور أو رموز التحقق لأي شخص.'),'privacy'),
    (jsonb_build_object('title','معلومات تساعد الدعم','body','اكتب الخطوات التي سبقت المشكلة ونوع الجهاز أو المتصفح إن كان ذلك مهمًا.'),'other')
  ) x(v,c) where c=coalesce(p_category,'other');
$$;
revoke all on function public.rivo_support_suggestions(text) from public;
grant execute on function public.rivo_support_suggestions(text) to anon,authenticated;

-- Realtime for a fast chat experience.
do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rivo_support_messages') then alter publication supabase_realtime add table public.rivo_support_messages; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rivo_support_tickets') then alter publication supabase_realtime add table public.rivo_support_tickets; end if;
exception when undefined_table then null; end $$;

-- Optional but useful: notification trigger using Rivo's existing notifications table when present.
do $$ begin
  if to_regclass('public.rivo_notifications') is not null then
    create or replace function public.rivo_support_notify() returns trigger language plpgsql security definer set search_path=public as $fn$
    declare tid public.rivo_support_tickets; receiver uuid;
    begin
      select * into tid from public.rivo_support_tickets where id=new.ticket_id;
      if tid.user_id = new.sender_id then
        receiver := tid.assigned_admin_id;
      else
        receiver := tid.user_id;
      end if;
      if receiver is not null and receiver <> new.sender_id then
        begin
          perform public.rivo_write_notification(receiver,new.sender_id,'message','رسالة جديدة في طلب الدعم',jsonb_build_object('ticket_id',new.ticket_id,'support',true));
        exception when others then null; end;
      end if;
      return new;
    end;$fn$;
    drop trigger if exists trg_rivo_support_notify on public.rivo_support_messages;
    create trigger trg_rivo_support_notify after insert on public.rivo_support_messages for each row execute function public.rivo_support_notify();
  end if;
end $$;
