
-- Rivo targeted additions: voice messages, post reports, admin account editing.

-- Private voice storage bucket.
insert into storage.buckets (id, name, public)
values ('rivo-voice','rivo-voice',false)
on conflict (id) do update set public=false;

create table if not exists public.rivo_voice_messages (
  id bigint generated by default as identity primary key,
  message_id bigint not null unique references public.rivo_messages(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  duration_ms integer not null check (duration_ms between 1 and 300000),
  mime_type text not null default 'audio/webm',
  created_at timestamptz not null default now()
);
create index if not exists rivo_voice_sender_receiver_idx on public.rivo_voice_messages(sender_id,receiver_id,created_at desc);
alter table public.rivo_voice_messages enable row level security;
drop policy if exists "rivo_voice_select_participants" on public.rivo_voice_messages;
create policy "rivo_voice_select_participants" on public.rivo_voice_messages for select to authenticated
using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "rivo_voice_storage_insert_owner" on storage.objects;
create policy "rivo_voice_storage_insert_owner" on storage.objects for insert to authenticated
with check (bucket_id='rivo-voice' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "rivo_voice_storage_select_participants" on storage.objects;
create policy "rivo_voice_storage_select_participants" on storage.objects for select to authenticated
using (bucket_id='rivo-voice' and exists(select 1 from public.rivo_voice_messages v where v.storage_path = name and (v.sender_id=auth.uid() or v.receiver_id=auth.uid())));
drop policy if exists "rivo_voice_storage_delete_owner" on storage.objects;
create policy "rivo_voice_storage_delete_owner" on storage.objects for delete to authenticated
using (bucket_id='rivo-voice' and (storage.foldername(name))[1] = auth.uid()::text);


create or replace function public.rivo_send_voice_message(p_receiver_username text,p_storage_path text,p_duration_ms int,p_mime_type text default 'audio/webm')
returns jsonb language plpgsql security definer set search_path=public as $$
declare me public.profiles; target public.profiles; msg public.rivo_messages; voice public.rivo_voice_messages; can_receive text; are_friends boolean:=false; path text:=trim(coalesce(p_storage_path,''));
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  if p_duration_ms is null or p_duration_ms < 1 or p_duration_ms > 300000 then raise exception 'Invalid voice duration'; end if;
  if path = '' or path not like auth.uid()::text || '/voice/%' then raise exception 'Invalid voice storage path'; end if;
  select * into me from public.profiles where id=auth.uid();
  select * into target from public.profiles where username=lower(trim(both '@' from p_receiver_username));
  if me.id is null or target.id is null then raise exception 'User not found'; end if;
  if me.id=target.id then raise exception 'You cannot message yourself'; end if;
  if me.is_banned then raise exception 'Your account is blocked'; end if;
  if target.is_banned then raise exception 'This account is unavailable'; end if;
  can_receive:=coalesce(target.private_data->'messageSettings'->>'whoCanMessage','everyone');
  if can_receive='nobody' then raise exception 'This user has closed their messages'; end if;
  are_friends:=coalesce(target.public_data->'friends','[]'::jsonb) ? me.username;
  if can_receive='friends' and not are_friends then raise exception 'This user accepts messages from friends only'; end if;
  insert into public.rivo_messages(sender_id,receiver_id,content) values(me.id,target.id,'[voice]') returning * into msg;
  insert into public.rivo_voice_messages(message_id,sender_id,receiver_id,storage_path,duration_ms,mime_type) values(msg.id,me.id,target.id,path,p_duration_ms,coalesce(nullif(p_mime_type,''),'audio/webm')) returning * into voice;
  perform public.rivo_write_notification(target.id,me.id,'message',me.username||' sent you a voice message',jsonb_build_object('message_id',msg.id,'username',me.username,'voice',true));
  return jsonb_build_object('id',msg.id,'sender_username',me.username,'receiver_username',target.username,'content','[voice]','message_type','voice','voice_path',voice.storage_path,'voice_duration',voice.duration_ms,'created_at',msg.created_at);
end; $$;
revoke all on function public.rivo_send_voice_message(text,text,int,text) from public;
grant execute on function public.rivo_send_voice_message(text,text,int,text) to authenticated;

-- Report system.
create table if not exists public.rivo_post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.rivo_posts(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null default 'reported',
  created_at timestamptz not null default now(),
  unique(post_id,reporter_id)
);
create index if not exists rivo_post_reports_post_idx on public.rivo_post_reports(post_id,created_at desc);
alter table public.rivo_post_reports enable row level security;
create or replace function public.rivo_report_post(p_post_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); owner_id uuid; cnt int; deleted boolean:=false;
begin
  if me is null then raise exception 'Not signed in'; end if;
  select user_id into owner_id from public.rivo_posts where id=p_post_id;
  if owner_id is null then raise exception 'Post not found'; end if;
  if owner_id = me then raise exception 'You cannot report your own post'; end if;
  insert into public.rivo_post_reports(post_id,reporter_id) values(p_post_id,me) on conflict(post_id,reporter_id) do nothing;
  select count(*)::int into cnt from public.rivo_post_reports where post_id=p_post_id;
  if cnt >= 10 then
    delete from public.rivo_posts where id=p_post_id;
    deleted:=true;
  end if;
  return jsonb_build_object('reported',true,'reports',cnt,'deleted',deleted,'id',p_post_id);
end; $$;
revoke all on function public.rivo_report_post(bigint) from public;
grant execute on function public.rivo_report_post(bigint) to authenticated;

-- Add voice metadata to the existing message read RPC.
create or replace function public.rivo_get_messages(p_other_username text, p_limit int default 80)
returns setof jsonb language sql security definer set search_path = public as $$
  select jsonb_build_object(
    'id', m.id,
    'sender_username', s.username,
    'receiver_username', r.username,
    'content', m.content,
    'message_type', case when v.id is null then 'text' else 'voice' end,
    'voice_path', v.storage_path,
    'voice_duration', v.duration_ms,
    'created_at', m.created_at
  )
  from public.rivo_messages m
  join public.profiles s on s.id=m.sender_id
  join public.profiles r on r.id=m.receiver_id
  left join public.rivo_voice_messages v on v.message_id=m.id
  where ((m.sender_id=auth.uid() and m.receiver_id=(select id from public.profiles where username=lower(trim(both '@' from p_other_username))))
      or (m.receiver_id=auth.uid() and m.sender_id=(select id from public.profiles where username=lower(trim(both '@' from p_other_username)))))
  order by m.created_at desc
  limit greatest(1,least(coalesce(p_limit,80),200));
$$;
revoke all on function public.rivo_get_messages(text,int) from public;
grant execute on function public.rivo_get_messages(text,int) to authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rivo_voice_messages') then alter publication supabase_realtime add table public.rivo_voice_messages; end if;
end $$;

-- Admin update RPC used by the Edge Function to safely update the public profile fields.
create or replace function public.rivo_admin_update_profile(p_current_username text,p_new_username text,p_display_name text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare target public.profiles; oldu text:=lower(trim(both '@' from p_current_username)); newu text:=lower(trim(both '@' from p_new_username));
begin
  if not public.rivo_is_admin(auth.uid()) then raise exception 'Access denied'; end if;
  select * into target from public.profiles where username=oldu for update;
  if target.id is null then raise exception 'User not found'; end if;
  if newu is null or newu !~ '^[a-z0-9][a-z0-9._-]{1,24}[a-z0-9]$' then raise exception 'Invalid username'; end if;
  if newu <> oldu and exists(select 1 from public.profiles where username=newu) then raise exception 'Username already exists'; end if;
  update public.profiles set username=newu, public_data=jsonb_set(coalesce(public_data,'{}'::jsonb),'{displayName}',to_jsonb(coalesce(nullif(trim(p_display_name),''),newu)),true), updated_at=now() where id=target.id;
  return jsonb_build_object('user_id',target.id,'username',newu,'display_name',coalesce(nullif(trim(p_display_name),''),newu));
end; $$;
revoke all on function public.rivo_admin_update_profile(text,text,text) from public;
grant execute on function public.rivo_admin_update_profile(text,text,text) to authenticated;
